import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

const navy=Color(0xFF101A2C), gold=Color(0xFFD4AF37);
void main()=>runApp(const App());
class App extends StatefulWidget{const App({super.key});@override State<App> createState()=>_AppState();}
class _AppState extends State<App>{bool dark=true;@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'میراث ملک',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:gold)),darkTheme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:gold,brightness:Brightness.dark)),themeMode:dark?ThemeMode.dark:ThemeMode.light,home:Login(onTheme:(v)=>setState(()=>dark=v)));}
class DB{
 static Future<List<Map<String,dynamic>>> files()async{final p=await SharedPreferences.getInstance();final a=jsonDecode(p.getString('files')??'[]') as List;return a.map((e)=>Map<String,dynamic>.from(e)).toList();}
 static Future<void> saveFiles(List<Map<String,dynamic>> a)async{final p=await SharedPreferences.getInstance();await p.setString('files',jsonEncode(a));}
 static Future<List<String>> customers()async{final p=await SharedPreferences.getInstance();return p.getStringList('customers')??[];}
 static Future<void> saveCustomers(List<String> a)async{final p=await SharedPreferences.getInstance();await p.setStringList('customers',a);}
 static Future<String> get(String k)async{final p=await SharedPreferences.getInstance();return p.getString(k)??'';}
 static Future<void> set(String k,String v)async{final p=await SharedPreferences.getInstance();await p.setString(k,v);}
}
class Login extends StatefulWidget{final ValueChanged<bool> onTheme;const Login({super.key,required this.onTheme});@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final u=TextEditingController(),p=TextEditingController();bool hide=true;Future<void> go()async{final saved=await DB.get('password');final ok=u.text=='admin'&&p.text==(saved.isEmpty?'1234':saved);if(ok&&mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Home(onTheme:widget.onTheme)));else if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('نام کاربری یا رمز عبور اشتباه است')));}@override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:navy,body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[Container(width:90,height:90,decoration:BoxDecoration(color:gold,borderRadius:BorderRadius.circular(25)),child:const Icon(Icons.apartment,size:52,color:navy)),const SizedBox(height:14),const Text('میراث ملک',style:TextStyle(fontSize:31,fontWeight:FontWeight.w900)),const Text('سیستم مدیریت هوشمند دپارتمان املاک'),const SizedBox(height:25),TextField(controller:u,decoration:const InputDecoration(labelText:'نام کاربری',prefixIcon:Icon(Icons.person))),const SizedBox(height:12),TextField(controller:p,obscureText:hide,decoration:InputDecoration(labelText:'رمز عبور',prefixIcon:const Icon(Icons.lock),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)))),const SizedBox(height:18),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:go,child:const Text('ورود به سامانه'))),const SizedBox(height:10),const Text('مدیریت مهندس مجتبی صفری • مدیر فروش خانم طهماسبی پور',textAlign:TextAlign.center,style:TextStyle(fontSize:12))]))))));}
class Home extends StatefulWidget{final ValueChanged<bool> onTheme;const Home({super.key,required this.onTheme});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0;List<Map<String,dynamic>> files=[];List<String> customers=[];@override void initState(){super.initState();load();}Future<void>load()async{files=await DB.files();customers=await DB.customers();if(mounted)setState((){});}@override Widget build(BuildContext c){final pages=[Dashboard(files:files,customers:customers,onSaved:load),Files(files:files,onSaved:load),Customers(items:customers,onSaved:load),Messages(items:customers),const Commission(),Settings(onTheme:widget.onTheme)];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('میراث ملک'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard),label:'خانه'),NavigationDestination(icon:Icon(Icons.home_work),label:'فایل‌ها'),NavigationDestination(icon:Icon(Icons.people),label:'مشتریان'),NavigationDestination(icon:Icon(Icons.message),label:'پیام'),NavigationDestination(icon:Icon(Icons.calculate),label:'کمیسیون'),NavigationDestination(icon:Icon(Icons.settings),label:'تنظیمات')]));}}
class Dashboard extends StatelessWidget{final List<Map<String,dynamic>> files;final List<String> customers;final VoidCallback onSaved;const Dashboard({super.key,required this.files,required this.customers,required this.onSaved});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:navy,borderRadius:BorderRadius.circular(22)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('دپارتمان میراث ملک',style:TextStyle(color:gold,fontSize:28,fontWeight:FontWeight.w900)),Text('مدیریت مهندس مجتبی صفری',style:TextStyle(color:Colors.white)),Text('مدیر فروش خانم طهماسبی پور',style:TextStyle(color:Colors.white70))])),const SizedBox(height:15),Row(children:[_stat('فایل',files.length,Icons.home_work),_stat('مشتری',customers.length,Icons.people)]),const SizedBox(height:15),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>FileForm(onSaved:onSaved))),icon:const Icon(Icons.add),label:const Text('ثبت فایل جدید')),const Card(child:Padding(padding:EdgeInsets.all(14),child:Text('لینک آگهی دیوار را وارد کن تا اطلاعات عمومی ملک و تصاویر در فایل ثبت شود. شماره خصوصی مالک فقط با دسترسی رسمی و رضایت خود مالک قابل دریافت است.')))]);static Widget _stat(String t,int n,IconData i)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(15),child:Row(children:[Icon(i,color:gold),const SizedBox(width:8),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$n',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),Text(t)])]))));}
class Files extends StatefulWidget{final List<Map<String,dynamic>> files;final VoidCallback onSaved;const Files({super.key,required this.files,required this.onSaved});@override State<Files> createState()=>_FilesState();}
class _FilesState extends State<Files>{String q='';@override Widget build(BuildContext c){final a=widget.files.where((x)=>'${x['title']} ${x['code']} ${x['ownerPhone']} ${x['address']}'.contains(q)).toList();return Column(children:[Padding(padding:const EdgeInsets.all(12),child:TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(labelText:'جستجوی فایل',prefixIcon:Icon(Icons.search)))),Expanded(child:a.isEmpty?const Center(child:Text('فایلی ثبت نشده')):ListView.builder(itemCount:a.length,itemBuilder:(c,i)=>Card(child:ListTile(title:Text('${a[i]['title']}'),subtitle:Text('کد ${a[i]['code']} • ${a[i]['price']}\nمالک: ${a[i]['ownerName']} • ${a[i]['ownerPhone']}'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Details(file:a[i],onSaved:widget.onSaved)))))))]);}}
class Details extends StatelessWidget{final Map<String,dynamic> file;final VoidCallback onSaved;const Details({super.key,required this.file,required this.onSaved});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text('${file['title']}')),body:ListView(padding:const EdgeInsets.all(16),children:[for(final e in {'کد':'code','نوع':'type','معامله':'deal','متراژ':'area','قیمت':'price','آدرس':'address','مالک':'ownerName','شماره مالک':'ownerPhone','توضیحات':'description'}.entries)Card(child:Padding(padding:const EdgeInsets.all(12),child:Text('${e.key}: ${file[e.value]??''}'))),if('${file['divarLink']??''}'.isNotEmpty)FilledButton.icon(onPressed:()=>launchUrl(Uri.parse('${file['divarLink']}')),icon:const Icon(Icons.open_in_new),label:const Text('باز کردن لینک دیوار')),if('${file['ownerPhone']??''}'.isNotEmpty)OutlinedButton.icon(onPressed:()=>launchUrl(Uri(scheme:'tel',path:'${file['ownerPhone']}')),icon:const Icon(Icons.call),label:const Text('تماس با مالک')),if(file['images'] is List)...(file['images'] as List).map((x)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Image.network('$x',height:160,fit:BoxFit.cover))),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>FileForm(existing:file,onSaved:onSaved))),child:const Text('ویرایش فایل'))]));}}
class FileForm extends StatefulWidget{final Map<String,dynamic>? existing;final VoidCallback onSaved;const FileForm({super.key,this.existing,required this.onSaved});@override State<FileForm> createState()=>_FileFormState();}
class _FileFormState extends State<FileForm>{late TextEditingController title,type,deal,area,price,address,owner,phone,desc,link,key,token;bool loading=false;String msg='';@override void initState(){super.initState();final x=widget.existing??{};title=TextEditingController(text:'${x['title']??''}');type=TextEditingController(text:'${x['type']??'آپارتمان'}');deal=TextEditingController(text:'${x['deal']??'فروش'}');area=TextEditingController(text:'${x['area']??''}');price=TextEditingController(text:'${x['price']??''}');address=TextEditingController(text:'${x['address']??''}');owner=TextEditingController(text:'${x['ownerName']??''}');phone=TextEditingController(text:'${x['ownerPhone']??''}');desc=TextEditingController(text:'${x['description']??''}');link=TextEditingController(text:'${x['divarLink']??''}');key=TextEditingController();token=TextEditingController();}
String? postToken(){for(final r in [RegExp(r'divar\.ir/v/([A-Za-z0-9_-]{6,20})'),RegExp(r'divar\.ir/[^/]+/[^/]+/([A-Za-z0-9_-]{6,20})')]){final m=r.firstMatch(link.text);if(m!=null)return m.group(1);}return null;}
Future<void> importDivar()async{final t=postToken();if(t==null){setState(()=>msg='لینک دیوار معتبر نیست');return;}if(key.text.trim().isEmpty){setState(()=>msg='API Key رسمی دیوار را وارد کن');return;}setState(()=>loading=true);try{final r=await http.get(Uri.parse('https://open-api.divar.ir/v1/open-platform/finder/post/$t'),headers:{'x-api-key':key.text.trim()});final j=jsonDecode(r.body);if(r.statusCode<200||r.statusCode>299)throw Exception(j['message']??r.statusCode);final d=Map<String,dynamic>.from(j['data']??{});final p=d['price'];final imgs=d['images'] is List?(d['images'] as List).map((e)=>'$e').toList():[];setState((){title.text='${d['title']??d['prefilled_title']??''}';area.text='${d['size']??d['area']??''}';price.text=p is Map?'${p['value']??''}':'${p??''}';address.text='${j['address']??j['district']??address.text}';desc.text='${d['description']??''}';msg='اطلاعات عمومی آگهی وارد شد؛ شماره خصوصی مالک از API عمومی دیوار ارسال نمی‌شود.';});await DB.set('images',jsonEncode(imgs));}catch(e){setState(()=>msg='خطا: $e');}finally{if(mounted)setState(()=>loading=false);}}
Future<void> ownerPhone()async{if(key.text.isEmpty||token.text.isEmpty){setState(()=>msg='API Key و Access Token رسمی لازم است');return;}try{final r=await http.post(Uri.parse('https://open-api.divar.ir/v1/open-platform/users'),headers:{'x-api-key':key.text,'Authorization':'Bearer ${token.text}','Content-Type':'application/json'},body:'{}');final j=jsonDecode(r.body);if(r.statusCode>=200&&r.statusCode<300&&j['phone_numbers'] is List&&(j['phone_numbers'] as List).isNotEmpty){phone.text='${j['phone_numbers'][0]}';setState(()=>msg='شماره مالک مجاز دریافت شد');}else{setState(()=>msg='شماره برنگشت؛ مالک باید اجازه USER_PHONE داده باشد');}}catch(e){setState(()=>msg='خطا در دریافت شماره: $e');}}
Future<void> save()async{final all=await DB.files();final code=widget.existing!=null?'${widget.existing!['code']}':'MM-${DateTime.now().millisecondsSinceEpoch.toString().substring(5)}';final im=await DB.get('images');final x={'code':code,'title':title.text,'type':type.text,'deal':deal.text,'area':area.text,'price':price.text,'address':address.text,'ownerName':owner.text,'ownerPhone':phone.text,'description':desc.text,'divarLink':link.text,'images':im.isEmpty?[]:jsonDecode(im),'updated':DateFormat('yyyy/MM/dd HH:mm').format(DateTime.now())};final i=all.indexWhere((e)=>e['code']==code);if(i>=0)all[i]=x;else all.add(x);await DB.saveFiles(all);if(phone.text.trim().isNotEmpty){final cs=await DB.customers();if(!cs.contains(phone.text.trim())){cs.add(phone.text.trim());await DB.saveCustomers(cs);}}widget.onSaved();if(mounted)Navigator.pop(context);}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.existing==null?'ثبت فایل':'ویرایش فایل')),body:ListView(padding:const EdgeInsets.all(16),children:[f(title,'عنوان'),f(type,'نوع ملک'),f(deal,'نوع معامله'),f(area,'متراژ'),f(price,'قیمت'),f(address,'آدرس'),f(owner,'نام مالک'),f(phone,'شماره مالک',keyboard:TextInputType.phone),f(link,'لینک دیوار'),Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[const Text('اتصال رسمی دیوار'),f(key,'API Key دیوار',obscure:true),f(token,'Access Token رسمی',obscure:true),Row(children:[Expanded(child:FilledButton.icon(onPressed:loading?null:importDivar,icon:const Icon(Icons.download),label:Text(loading?'دریافت...':'ورود خودکار مشخصات'))),IconButton(onPressed:ownerPhone,icon:const Icon(Icons.phone))]),if(msg.isNotEmpty)Text(msg)]))),f(desc,'توضیحات',multi:true),FilledButton.icon(onPressed:save,icon:const Icon(Icons.save),label:const Text('ثبت و ذخیره'))]));Widget f(TextEditingController x,String l,{bool multi=false,bool obscure=false,TextInputType? keyboard})=>Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(controller:x,maxLines:multi?5:1,obscureText:obscure,keyboardType:keyboard,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder())));}
class Customers extends StatefulWidget{final List<String> items;final VoidCallback onSaved;const Customers({super.key,required this.items,required this.onSaved});@override State<Customers> createState()=>_CustomersState();}
class _CustomersState extends State<Customers>{final n=TextEditingController();@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:n,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'شماره مشتری'))),IconButton(onPressed:()async{final v=n.text.trim();if(v.isEmpty)return;final a=await DB.customers();if(!a.contains(v)){a.add(v);await DB.saveCustomers(a);}n.clear();widget.onSaved();setState((){});},icon:const Icon(Icons.add_circle))])),Expanded(child:ListView(children:widget.items.map((v)=>ListTile(title:Text(v),leading:const Icon(Icons.phone),trailing:Wrap(children:[IconButton(onPressed:()=>launchUrl(Uri(scheme:'tel',path:v)),icon:const Icon(Icons.call)),IconButton(onPressed:()=>launchUrl(Uri(scheme:'sms',path:v,queryParameters:{'body':'سلام، از دپارتمان میراث ملک پیام می‌دهیم.'})),icon:const Icon(Icons.sms))]))).toList()))]);}
class Messages extends StatelessWidget{final List<String> items;const Messages({super.key,required this.items});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('ارسال پیام به مشتریان',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...items.map((v)=>Card(child:ListTile(title:Text(v),trailing:IconButton(onPressed:()=>launchUrl(Uri(scheme:'sms',path:v,queryParameters:{'body':'سلام، از دپارتمان میراث ملک پیام می‌دهیم.'})),icon:const Icon(Icons.send))))) ]);}
class Commission extends StatefulWidget{const Commission({super.key});@override State<Commission> createState()=>_CommissionState();}
class _CommissionState extends State<Commission>{final a=TextEditingController();double pct=.5,vat=10;@override Widget build(BuildContext c){final x=double.tryParse(a.text)??0,b=x*pct/100,t=b*vat/100;return ListView(padding:const EdgeInsets.all(16),children:[const Text('محاسبه کمیسیون',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),TextField(controller:a,onChanged:(_)=>setState((){}),keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'مبلغ معامله')),DropdownButtonFormField<double>(value:pct,items:const[.25,.5,1].map((v)=>DropdownMenuItem(value:v,child:Text('$v درصد'))).toList(),onChanged:(v)=>setState(()=>pct=v??.5),decoration:const InputDecoration(labelText:'درصد کمیسیون')),DropdownButtonFormField<double>(value:vat,items:const[0,10].map((v)=>DropdownMenuItem(value:v,child:Text('$v درصد'))).toList(),onChanged:(v)=>setState(()=>vat=v??10),decoration:const InputDecoration(labelText:'مالیات')),const SizedBox(height:15),Card(child:Padding(padding:const EdgeInsets.all(16),child:Text('کمیسیون: ${b.toStringAsFixed(0)}\nمالیات: ${t.toStringAsFixed(0)}\nنهایی: ${(b+t).toStringAsFixed(0)}',style:const TextStyle(fontSize:18))))];}}
class Settings extends StatefulWidget{final ValueChanged<bool> onTheme;const Settings({super.key,required this.onTheme});@override State<Settings> createState()=>_SettingsState();}
class _SettingsState extends State<Settings>{bool dark=true;final p=TextEditingController();@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[SwitchListTile(title:const Text('حالت تیره'),value:dark,onChanged:(v){setState(()=>dark=v);widget.onTheme(v);}),const ListTile(title:Text('مدیریت'),subtitle:Text('مهندس مجتبی صفری • مدیر فروش خانم طهماسبی پور')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'رمز جدید مدیر')),FilledButton(onPressed:()async{if(p.text.length>=4)await DB.set('password',p.text);p.clear();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('رمز ذخیره شد')));},child:const Text('تغییر رمز')),const Card(child:Padding(padding:EdgeInsets.all(14),child:Text('شماره خصوصی دیوار فقط با OAuth و رضایت صاحب حساب قابل دریافت است. GET_POST فقط اطلاعات عمومی آگهی را برمی‌گرداند.')))]);}
