import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

const navy=Color(0xFF101A2C); const gold=Color(0xFFD4AF37);
void main(){runApp(const MirathApp());}

class MirathApp extends StatefulWidget{const MirathApp({super.key});@override State<MirathApp> createState()=>_MirathAppState();}
class _MirathAppState extends State<MirathApp>{bool dark=true;@override Widget build(BuildContext c){return MaterialApp(debugShowCheckedModeBanner:false,title:'میراث ملک',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:gold)),darkTheme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:gold,brightness:Brightness.dark)),themeMode:dark?ThemeMode.dark:ThemeMode.light,home:Login(onTheme:(v)=>setState(()=>dark=v)));}}

class DB{
 static Future<List<Map<String,dynamic>>> files()async{final p=await SharedPreferences.getInstance();final raw=p.getString('files')??'[]';final a=jsonDecode(raw) as List;return a.map((e)=>Map<String,dynamic>.from(e)).toList();}
 static Future<void> saveFiles(List<Map<String,dynamic>> a)async{final p=await SharedPreferences.getInstance();await p.setString('files',jsonEncode(a));}
 static Future<List<String>> customers()async{final p=await SharedPreferences.getInstance();return p.getStringList('customers')??[];}
 static Future<void> saveCustomers(List<String> a)async{final p=await SharedPreferences.getInstance();await p.setStringList('customers',a);}
 static Future<String> get(String k)async{final p=await SharedPreferences.getInstance();return p.getString(k)??'';}
 static Future<void> set(String k,String v)async{final p=await SharedPreferences.getInstance();await p.setString(k,v);}
}

class Login extends StatefulWidget{final ValueChanged<bool> onTheme;const Login({super.key,required this.onTheme});@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final u=TextEditingController(),p=TextEditingController();bool hide=true;
 Future<void> login()async{final saved=await DB.get('password');final pass=saved.isEmpty?'1234':saved; if(u.text=='admin'&&p.text==pass&&mounted){Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Home(onTheme:widget.onTheme)));}else{if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('نام کاربری یا رمز عبور اشتباه است')));}}
 @override Widget build(BuildContext c){return Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:navy,body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:<Widget>[Container(width:90,height:90,decoration:BoxDecoration(color:gold,borderRadius:BorderRadius.circular(25)),child:const Icon(Icons.apartment,size:52,color:navy)),const SizedBox(height:14),const Text('میراث ملک',style:TextStyle(fontSize:31,fontWeight:FontWeight.w900)),const Text('سیستم مدیریت هوشمند دپارتمان املاک'),const SizedBox(height:25),TextField(controller:u,decoration:const InputDecoration(labelText:'نام کاربری',prefixIcon:Icon(Icons.person))),const SizedBox(height:12),TextField(controller:p,obscureText:hide,decoration:InputDecoration(labelText:'رمز عبور',prefixIcon:const Icon(Icons.lock),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility:Icons.visibility_off)))),const SizedBox(height:18),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:login,child:const Text('ورود به سامانه'))),const SizedBox(height:10),const Text('مدیریت مهندس مجتبی صفری • مدیر فروش خانم طهماسبی پور',textAlign:TextAlign.center,style:TextStyle(fontSize:12))]))))));}}

class Home extends StatefulWidget{final ValueChanged<bool> onTheme;const Home({super.key,required this.onTheme});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0;List<Map<String,dynamic>> files=[];List<String> customers=[];
 @override void initState(){super.initState();load();}
 Future<void> load()async{files=await DB.files();customers=await DB.customers();if(mounted)setState((){});}
 @override Widget build(BuildContext c){Widget body;switch(tab){case 1:body=FilesPage(items:files,onSaved:load);break;case 2:body=CustomersPage(items:customers,onSaved:load);break;case 3:body=MessagesPage(items:customers);break;case 4:body=const CommissionPage();break;case 5:body=SettingsPage(onTheme:widget.onTheme);break;default:body=Dashboard(files:files,customers:customers,onSaved:load);}return Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('میراث ملک'),actions:<Widget>[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:body,bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const<NavigationDestination>[NavigationDestination(icon:Icon(Icons.dashboard),label:'خانه'),NavigationDestination(icon:Icon(Icons.home_work),label:'فایل‌ها'),NavigationDestination(icon:Icon(Icons.people),label:'مشتریان'),NavigationDestination(icon:Icon(Icons.message),label:'پیام'),NavigationDestination(icon:Icon(Icons.calculate),label:'کمیسیون'),NavigationDestination(icon:Icon(Icons.settings),label:'تنظیمات')]));}}

class Dashboard extends StatelessWidget{final List<Map<String,dynamic>> files;final List<String> customers;final VoidCallback onSaved;const Dashboard({super.key,required this.files,required this.customers,required this.onSaved});
 @override Widget build(BuildContext c){return ListView(padding:const EdgeInsets.all(16),children:<Widget>[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:navy,borderRadius:BorderRadius.circular(22)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[Text('دپارتمان میراث ملک',style:TextStyle(color:gold,fontSize:28,fontWeight:FontWeight.w900)),Text('مدیریت مهندس مجتبی صفری',style:TextStyle(color:Colors.white)),Text('مدیر فروش خانم طهماسبی پور',style:TextStyle(color:Colors.white70))])),const SizedBox(height:14),Row(children:<Widget>[_stat('فایل',files.length,Icons.home_work),_stat('مشتری',customers.length,Icons.people)]),const SizedBox(height:14),FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>FileForm(onSaved:onSaved))),icon:const Icon(Icons.add),label:const Text('ثبت فایل جدید')),const Card(child:Padding(padding:EdgeInsets.all(14),child:Text('لینک آگهی دیوار را وارد کن تا اطلاعات عمومی ملک و تصاویر وارد فایل شوند. شماره خصوصی مالک فقط از مسیر رسمی دیوار و با رضایت صاحب حساب قابل دریافت است.')))]);}
 static Widget _stat(String title,int n,IconData icon){return Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(15),child:Row(children:<Widget>[Icon(icon,color:gold),const SizedBox(width:8),Column(crossAxisAlignment:CrossAxisAlignment.start,children:<Widget>[Text('$n',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),Text(title)])]))));}}

class FilesPage extends StatefulWidget{final List<Map<String,dynamic>> items;final VoidCallback onSaved;const FilesPage({super.key,required this.items,required this.onSaved});@override State<FilesPage> createState()=>_FilesPageState();}
class _FilesPageState extends State<FilesPage>{String search='';@override Widget build(BuildContext c){final list=itemsFiltered();return Column(children:<Widget>[Padding(padding:const EdgeInsets.all(12),child:TextField(onChanged:(v)=>setState(()=>search=v),decoration:const InputDecoration(labelText:'جستجوی فایل',prefixIcon:Icon(Icons.search)))),Expanded(child:list.isEmpty?const Center(child:Text('فایلی ثبت نشده')):ListView.builder(itemCount:list.length,itemBuilder:(c,i){final x=list[i];return Card(child:ListTile(title:Text('${x['title']}'),subtitle:Text('کد ${x['code']} • ${x['price']}\nمالک: ${x['ownerName']} • ${x['ownerPhone']}'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>DetailsPage(file:x,onSaved:widget.onSaved))));})))]);}
 List<Map<String,dynamic>> itemsFiltered(){return widget.items.where((x)=>'${x['title']} ${x['code']} ${x['address']} ${x['ownerPhone']}'.contains(search)).toList();}}

class DetailsPage extends StatelessWidget{final Map<String,dynamic> file;final VoidCallback onSaved;const DetailsPage({super.key,required this.file,required this.onSaved});
 @override Widget build(BuildContext c){final images=file['images'] is List?List<dynamic>.from(file['images'] as List):<dynamic>[];return Scaffold(appBar:AppBar(title:Text('${file['title']}')),body:ListView(padding:const EdgeInsets.all(16),children:<Widget>[_line('کد','${file['code']}'),_line('نوع ملک','${file['type']}'),_line('نوع معامله','${file['deal']}'),_line('متراژ','${file['area']}'),_line('قیمت','${file['price']}'),_line('آدرس','${file['address']}'),_line('نام مالک','${file['ownerName']}'),_line('شماره مالک','${file['ownerPhone']}'),_line('توضیحات','${file['description']}'),if('${file['divarLink']}'.isNotEmpty)FilledButton.icon(onPressed:()=>launchUrl(Uri.parse('${file['divarLink']}')),icon:const Icon(Icons.open_in_new),label:const Text('باز کردن لینک دیوار')),if('${file['ownerPhone']}'.isNotEmpty)OutlinedButton.icon(onPressed:()=>launchUrl(Uri(scheme:'tel',path:'${file['ownerPhone']}')),icon:const Icon(Icons.call),label:const Text('تماس با مالک')),if(images.isNotEmpty)SizedBox(height:180,child:ListView.builder(scrollDirection:Axis.horizontal,itemCount:images.length,itemBuilder:(c,i)=>Padding(padding:const EdgeInsets.all(4),child:Image.network('${images[i]}',width:230,fit:BoxFit.cover)))),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>FileForm(existing:file,onSaved:onSaved))),child:const Text('ویرایش فایل'))]));}
 Widget _line(String a,String b){return Card(child:Padding(padding:const EdgeInsets.all(12),child:Text('$a: $b')));}}

class FileForm extends StatefulWidget{final Map<String,dynamic>? existing;final VoidCallback onSaved;const FileForm({super.key,this.existing,required this.onSaved});@override State<FileForm> createState()=>_FileFormState();}
class _FileFormState extends State<FileForm>{late TextEditingController title,type,deal,area,price,address,owner,phone,description,link,apiKey,accessToken;bool loading=false;String message='';
 @override void initState(){super.initState();final x=widget.existing??{};title=_ctl(x['title']);type=_ctl(x['type']??'آپارتمان');deal=_ctl(x['deal']??'فروش');area=_ctl(x['area']);price=_ctl(x['price']);address=_ctl(x['address']);owner=_ctl(x['ownerName']);phone=_ctl(x['ownerPhone']);description=_ctl(x['description']);link=_ctl(x['divarLink']);apiKey=TextEditingController();accessToken=TextEditingController();}
 TextEditingController _ctl(dynamic v)=>TextEditingController(text:v==null?'':'$v');
 String? tokenFromLink(){final a=RegExp(r'divar\.ir/v/([A-Za-z0-9_-]{6,20})').firstMatch(link.text);if(a!=null)return a.group(1);final b=RegExp(r'divar\.ir/[^/]+/[^/]+/([A-Za-z0-9_-]{6,20})').firstMatch(link.text);return b?.group(1);}
 Future<void> importDivar()async{final token=tokenFromLink();if(token==null){setState(()=>message='لینک دیوار معتبر نیست');return;}if(apiKey.text.trim().isEmpty){setState(()=>message='API Key رسمی دیوار را وارد کن');return;}setState(()=>loading=true);try{final r=await http.get(Uri.parse('https://open-api.divar.ir/v1/open-platform/finder/post/$token'),headers:{'x-api-key':apiKey.text.trim()});final j=jsonDecode(r.body);if(r.statusCode<200||r.statusCode>299)throw Exception(j['message']??r.statusCode);final d=Map<String,dynamic>.from(j['data']??{});final p=d['price'];final imgs=d['images'] is List?(d['images'] as List).map((e)=>'$e').toList():<String>[];title.text='${d['title']??d['prefilled_title']??''}';area.text='${d['size']??d['area']??''}';price.text=p is Map?'${p['value']??''}':'${p??''}';address.text='${j['address']??j['district']??address.text}';description.text='${d['description']??''}';await DB.set('pending_images',jsonEncode(imgs));setState(()=>message='اطلاعات عمومی آگهی وارد شد. شماره خصوصی مالک در GET_POST دیوار ارائه نمی‌شود.');}catch(e){setState(()=>message='خطا در دریافت آگهی: $e');}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> getAuthorizedPhone()async{if(apiKey.text.isEmpty||accessToken.text.isEmpty){setState(()=>message='API Key و Access Token رسمی لازم است');return;}try{final r=await http.post(Uri.parse('https://open-api.divar.ir/v1/open-platform/users'),headers:{'x-api-key':apiKey.text,'Authorization':'Bearer ${accessToken.text}','Content-Type':'application/json'},body:'{}');final j=jsonDecode(r.body);if(r.statusCode>=200&&r.statusCode<300&&j['phone_numbers'] is List&&(j['phone_numbers'] as List).isNotEmpty){phone.text='${j['phone_numbers'][0]}';setState(()=>message='شماره مجاز مالک دریافت شد');}else{setState(()=>message='شماره دریافت نشد؛ مالک باید USER_PHONE را به برنامه رسمی شما اجازه داده باشد.');}}catch(e){setState(()=>message='خطا در دریافت شماره: $e');}}
 Future<void> save()async{final all=await DB.files();final code=widget.existing==null?'MM-${DateTime.now().millisecondsSinceEpoch.toString().substring(6)}':'${widget.existing!['code']}';final im=await DB.get('pending_images');final x=<String,dynamic>{'code':code,'title':title.text,'type':type.text,'deal':deal.text,'area':area.text,'price':price.text,'address':address.text,'ownerName':owner.text,'ownerPhone':phone.text,'description':description.text,'divarLink':link.text,'images':im.isEmpty?<String>[]:jsonDecode(im),'updated':DateFormat('yyyy/MM/dd HH:mm').format(DateTime.now())};final index=all.indexWhere((e)=>e['code']==code);if(index<0)all.add(x);else all[index]=x;await DB.saveFiles(all);if(phone.text.trim().isNotEmpty){final cs=await DB.customers();if(!cs.contains(phone.text.trim())){cs.add(phone.text.trim());await DB.saveCustomers(cs);}}widget.onSaved();if(mounted)Navigator.pop(context);}
 Widget f(TextEditingController c,String label,{bool multi=false,bool obscure=false,TextInputType? keyboard}){return Padding(padding:const EdgeInsets.only(bottom:9),child:TextField(controller:c,maxLines:multi?5:1,obscureText:obscure,keyboardType:keyboard,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));}
 @override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:Text(widget.existing==null?'ثبت فایل جدید':'ویرایش فایل')),body:ListView(padding:const EdgeInsets.all(16),children:<Widget>[f(title,'عنوان فایل'),f(type,'نوع ملک'),f(deal,'نوع معامله'),f(area,'متراژ'),f(price,'قیمت'),f(address,'آدرس'),f(owner,'نام مالک'),f(phone,'شماره مالک',keyboard:TextInputType.phone),f(link,'لینک آگهی دیوار'),Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:<Widget>[const Align(alignment:Alignment.centerRight,child:Text('اتصال رسمی دیوار',style:TextStyle(fontWeight:FontWeight.bold))),f(apiKey,'API Key دیوار',obscure:true),f(accessToken,'Access Token رسمی',obscure:true),Row(children:<Widget>[Expanded(child:FilledButton.icon(onPressed:loading?null:importDivar,icon:const Icon(Icons.download),label:Text(loading?'دریافت...':'ورود خودکار مشخصات'))),IconButton(onPressed:getAuthorizedPhone,icon:const Icon(Icons.phone))]),if(message.isNotEmpty)Align(alignment:Alignment.centerRight,child:Text(message))]))),f(description,'توضیحات',multi:true),FilledButton.icon(onPressed:save,icon:const Icon(Icons.save),label:const Text('ثبت و ذخیره فایل'))]));}}

class CustomersPage extends StatefulWidget{final List<String> items;final VoidCallback onSaved;const CustomersPage({super.key,required this.items,required this.onSaved});@override State<CustomersPage> createState()=>_CustomersPageState();}
class _CustomersPageState extends State<CustomersPage>{final n=TextEditingController();@override Widget build(BuildContext c){return Column(children:<Widget>[Padding(padding:const EdgeInsets.all(12),child:Row(children:<Widget>[Expanded(child:TextField(controller:n,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'شماره مشتری'))),IconButton(onPressed:()async{final v=n.text.trim();if(v.isEmpty)return;final a=await DB.customers();if(!a.contains(v)){a.add(v);await DB.saveCustomers(a);}n.clear();widget.onSaved();setState((){});},icon:const Icon(Icons.add_circle))])),Expanded(child:ListView.builder(itemCount:widget.items.length,itemBuilder:(c,i){final v=widget.items[i];return ListTile(title:Text(v),leading:const Icon(Icons.phone),trailing:Wrap(children:<Widget>[IconButton(onPressed:()=>launchUrl(Uri(scheme:'tel',path:v)),icon:const Icon(Icons.call)),IconButton(onPressed:()=>launchUrl(Uri(scheme:'sms',path:v,queryParameters:<String,String>{'body':'سلام، از دپارتمان میراث ملک پیام می‌دهیم.'})),icon:const Icon(Icons.sms))]));}))]);}}

class MessagesPage extends StatelessWidget{final List<String> items;const MessagesPage({super.key,required this.items});@override Widget build(BuildContext c){return ListView(padding:const EdgeInsets.all(16),children:<Widget>[const Text('ارسال پیام به مشتریان',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),for(final v in items)Card(child:ListTile(title:Text(v),trailing:IconButton(onPressed:()=>launchUrl(Uri(scheme:'sms',path:v,queryParameters:<String,String>{'body':'سلام، از دپارتمان میراث ملک پیام می‌دهیم.'})),icon:const Icon(Icons.send))))]);}}

class CommissionPage extends StatefulWidget{const CommissionPage({super.key});@override State<CommissionPage> createState()=>_CommissionPageState();}
class _CommissionPageState extends State<CommissionPage>{final amount=TextEditingController();double pct=.5,vat=10;@override Widget build(BuildContext c){final a=double.tryParse(amount.text)??0;final base=a*pct/100;final tax=base*vat/100;return ListView(padding:const EdgeInsets.all(16),children:<Widget>[const Text('محاسبه کمیسیون',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),TextField(controller:amount,onChanged:(_)=>setState((){}),keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'مبلغ معامله')),DropdownButtonFormField<double>(value:pct,items:<DropdownMenuItem<double>>[const DropdownMenuItem(value:.25,child:Text('۰٫۲۵ درصد')),const DropdownMenuItem(value:.5,child:Text('۰٫۵ درصد')),const DropdownMenuItem(value:1,child:Text('۱ درصد'))],onChanged:(v)=>setState(()=>pct=v??.5),decoration:const InputDecoration(labelText:'کمیسیون')),DropdownButtonFormField<double>(value:vat,items:<DropdownMenuItem<double>>[const DropdownMenuItem(value:0,child:Text('۰ درصد مالیات')),const DropdownMenuItem(value:10,child:Text('۱۰ درصد مالیات'))],onChanged:(v)=>setState(()=>vat=v??10),decoration:const InputDecoration(labelText:'مالیات')),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(16),child:Text('کمیسیون پایه: ${base.toStringAsFixed(0)}\nمالیات: ${tax.toStringAsFixed(0)}\nمبلغ نهایی: ${(base+tax).toStringAsFixed(0)}',style:const TextStyle(fontSize:18))))]));}}

class SettingsPage extends StatefulWidget{final ValueChanged<bool> onTheme;const SettingsPage({super.key,required this.onTheme});@override State<SettingsPage> createState()=>_SettingsPageState();}
class _SettingsPageState extends State<SettingsPage>{bool dark=true;final p=TextEditingController();@override Widget build(BuildContext c){return ListView(padding:const EdgeInsets.all(16),children:<Widget>[SwitchListTile(title:const Text('حالت تیره'),value:dark,onChanged:(v){setState(()=>dark=v);widget.onTheme(v);}),const ListTile(title:Text('مدیریت'),subtitle:Text('مهندس مجتبی صفری • مدیر فروش خانم طهماسبی پور')),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'رمز جدید مدیر')),FilledButton(onPressed:()async{if(p.text.length>=4)await DB.set('password',p.text);p.clear();if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('رمز ذخیره شد')));},child:const Text('تغییر رمز')),const Card(child:Padding(padding:EdgeInsets.all(14),child:Text('اتصال دیوار رسمی است. اطلاعات عمومی آگهی با GET_POST دریافت می‌شود. شماره خصوصی مالک فقط با USER_PHONE و رضایت/مجوز رسمی او قابل دریافت است.')))]);}}
